blueprint:
  name: Sensor to Tracker
  description: Sets a tracker based on a binary sensor for presence
  domain: automation
  input:
    source:
      name: Source
      description: The binary sensor to observe
      selector:
        entity:
          filter:
            - domain: binary_sensor
            - device_class: presence
    destination:
      name: Destination
      description: The tracker to set
      selector:
        entity:
          filter:
            - domain: device_tracker

mode: restart
max_exceeded: silent

triggers:
  - trigger: homeassistant
    event: start
  - trigger: state
    entity_id: !input source

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - action: device_tracker.see
            data:
              dev_id: !input destination
              location_name: home
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - action: device_tracker.see
            data:
              dev_id: !input destination
              location_name: not_home
    default:
      - action: device_tracker.see
        data:
          dev_id: !input destination
          location_name: unknown
